  
name: "CI"
on:
  push:
    branches:
      - master
      - NGSI-v2
      - NGSI-LD
  pull_request:
    branches:
      - master
      - NGSI-v2
      - NGSI-LD
  workflow_dispatch:

jobs:
  test-modules:
    name: Test Script
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false 
        fetch-depth: 0
        submodules: recursive
    - name: Build Images
      run: |
        ./services create test || true
    - name: Run Orion
      run: |
        ./services orion test && ./services stop test
    - name: Run Stellio
      run: |
        ./services stellio test && ./services stop test
    - name: Run Scorpio
      run: |
        ./services scorpio test && ./services stop test

